import { z } from "zod";
import { gameMetadataSchema, ISO_DATE_REGEX } from "./game.ts";

/**
 * Aggregated catalog (`dist/catalog.json`) generated by the games library CI
 * from all individual `catalog/games/<id>.json` files.
 */
export const SUPPORTED_CATALOG_SCHEMA_VERSION = 1;

export const gameCatalogSchema = z.object({
  schemaVersion: z.number().int().positive(),
  generatedAt: z.string().regex(ISO_DATE_REGEX, "generatedAt must be ISO 8601 UTC"),
  games: z.array(gameMetadataSchema),
});

export type GameCatalog = z.infer<typeof gameCatalogSchema>;
